export const COUNTRIES = [
    'United States',
    'Canada',
    'United Kingdom',
    'Australia',
    'Germany',
    'France',
    'India',
    'Japan',
    'Brazil',
    'Mexico',
    'South Korea',
    'China',
    'Italy',
    'Spain',
    'Netherlands',
    'Sweden',
    'Norway',
    'Denmark',
    'Switzerland',
    'Russia',
    'South Africa',
    'New Zealand',
    'Argentina',
    'Philippines',
    'Vietnam',
    'Thailand',
    'Other',
  ];